<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ setting('site.title') }}</title>

    <meta name="title" content="@yield('meta_title', setting('site.title'))">
    <meta name='description' content="@yield('meta_description', setting('site.description'))" />
    <meta name='keywords' content="@yield('meta_title', 'eskopi, e-learning bkpm, elearning bkpm')" />
    <!-- generated by seo_lite -->
    <!-- for Facebook -->
    <meta property="og:title" content="@yield('meta_title', setting('site.title'))" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="@yield('meta_description', setting('site.description'))" />
    <meta property="og:image" content="{{asset('storage/'.setting('site.logo'))}}" />
    <meta property="og:site_name" content="E-Learning BKPM" />
    <!--meta property="fb:app_id" content=""/-->
    <link rel="apple-touch-icon" sizes="57x57" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="//www.bkpm.go.id/assets/images/bkpm-ico/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="//www.bkpm.go.id/assets/images/bkpm-ico/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="//www.bkpm.go.id/assets/images/bkpm-ico/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="//www.bkpm.go.id/assets/images/bkpm-ico/favicon-16x16.png">
    <link rel="manifest" href="//www.bkpm.go.id/assets/images/bkpm-ico/manifest.json">

    <link rel="shortcut icon" href="{{asset('storage/'.setting('site.logo'))}}">
    <link rel="stylesheet" href="{{asset('frontend/styles/bootstrap.min.css')}}">
    <link href="{{asset('frontend/assets/css/font-awesome.min.css')}}" rel="stylesheet">
    <link href="{{asset('frontend/assets/css/style.css')}}" rel="stylesheet">
    <link href="{{asset('frontend/assets/css/responsive-style.css')}}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link href="https://unpkg.com/ionicons@4.3.0/dist/css/ionicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('frontend/assets/css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{asset('frontend/assets/css/owl.theme.default.min.css')}}">
    <link href="{{asset('frontend/styles/select2.min.css')}}" rel="stylesheet" />
    <link rel="stylesheet" href="{{asset('frontend/styles/main.css')}}">
    <link rel="stylesheet" href="{{asset('frontend/assets/css/custome.css')}}">
    <link rel="stylesheet" href="{{asset('frontend/assets/css/bootstrap-datepicker.min.css')}}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{{asset('frontend/scripts/popper.min.js')}}"></script>
    <script src="{{asset('frontend/scripts/bootstrap.min.js')}}"></script>
    <script src="{{asset('frontend/assets/js/owl.carousel.min.js')}}"></script>
    <script src="{{asset('frontend/assets/js/script.js')}}"></script>
    <script src="{{asset('frontend/assets/js/bootstrap-datepicker.js')}}"></script>
    <script src="https://unpkg.com/ionicons@4.3.0/dist/ionicons.js"></script>
    <script src="{{asset('frontend/scripts/select2.min.js')}}"></script>
    <script src="{{asset('frontend/scripts/sweetalert.min.js')}}"></script>
    <script src="{{asset('frontend/assets/js/bootstrap-datepicker.min.js')}}"></script>
    
     
    @stack('push_css')
    @yield('style')
  </head>
<body>
  <div id="wrapper">
    <div class="header">
      <div class="top">
        <div class="container">
          <div class="logo desktop"><a href="{{url('/')}}"><img style="width: 160px;" src="{{asset('storage/'.setting('site.logo'))}}" alt="" class="img-fluid"></a></div>
        </div>
        <div class="mobile showMobile"><button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
            aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="logo"><a href="{{url('/')}}"><img src="{{asset('storage/'.setting('site.logo'))}}" alt="" class="img-fluid"></a></div>
        </div>
      </div>
      <div class="menu-wrapper">
        <div class="container">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="clearfix full">
                <div class="navbar-nav float-left">
                  <a class="nav-item nav-link active" href="{{url('/')}}">Beranda </a>
                  @foreach (menuItem('frontend')->getItem as $m)
                  <a class="nav-item nav-link" target="{{$m->target}}" href="{{url($m->url)}}">{{ucwords($m->title)}}</a>
                  @endforeach
                  @auth
                  <a class="nav-item nav-link " href="{{url('/')}}">Forum </a>
                  @endauth
                </div>
                <div class="float-right right-menu">
                  <div class="navbar-nav">
                    @auth
                      <a href="{{ url('/my-course') }}">Diklat Saya</a>
                      <a href="javascript:" onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}</a>
                      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                          @csrf
                      </form>
                    @else
                      <a href="{{ route('login') }}">Login</a>
  
                      @if (Route::has('register'))
                          <a href="{{ route('register') }}">Register</a>
                      @endif
                    @endauth
                  </div>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>
      @if (auth()->check())
        <div style="height: 50px; padding: 10px 0px;">
          <div class="container">
            <div class="d-flex">
              <a href="{{url()->previous() === url()->current() ? url('/') : url()->previous()}}" class="btn btn-default">
                <i class="fa fa-chevron-left" aria-hidden="true"></i>
                Back
              </a>
            </div>
          </div>
        </div>
      @endif
    </div>
    @yield('content')
    <footer>
      <div class="copyright">
        <div class="container">
          <div class="copyright__text text-center">
            <p>Copyright @2019 <a href="{{url('/')}}">{{ config('app.name', 'Laravel') }}</a>, All right reserved.</p>
          </div>
        </div>
      </div>
    </footer>
  </div>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-145618947-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-145618947-1');
  </script>

  <script type="text/javascript" async>
        $.ajaxSetup({
            headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $(document).ready(function(){
          $('.datepicker').datepicker({
            setDate: new Date(),
            autoclose: true
          })
          $('.select2').select2();
          @if (session()->has('success_msg'))
            swal ( "Sukses!" ,  `{!!session()->get('success_msg')!!}` ,  "success" )
          @endif
          @if (session()->has('error_msg'))
            swal ( "Gagal!" ,  `{!!session()->get('error_msg')!!}` ,  "error" )
          @endif
          @if (session()->has('warning_msg'))
            swal ( "Awas!" ,  `{!!session()->get('warning_msg')!!}` ,  "warning" )
          @endif
          @if (session()->has('info_msg'))
            swal ( "Info!" ,  `{!!session()->get('info_msg')!!}` ,  "info" )
          @endif
        });
  </script>
  @stack('push_js')
  @yield('script')
</body>
</html>
