<!doctype html>
<html class="no-js">

<head>
  <meta charset="utf-8">
  <!-- start seo -->
  <meta name="title" content="@yield('meta_title', setting('site.title'))">
  <meta name='description' content="@yield('meta_description', setting('site.description'))" />
  <meta name='keywords' content="@yield('meta_title', 'eskopi, e-learning bkpm, elearning bkpm')" />
  <!-- generated by seo_lite -->
  <!-- for Facebook -->
  <meta property="og:title" content="@yield('meta_title', setting('site.title'))" />
  <meta property="og:type" content="website" />
  <meta property="og:description" content="@yield('meta_description', setting('site.description'))" />
  <meta property="og:image" content="{{asset('storage/'.setting('site.logo'))}}" />
  <meta property="og:site_name" content="E-Learning BKPM" />
  <!--meta property="fb:app_id" content=""/-->
  <link rel="apple-touch-icon" sizes="57x57" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="//www.bkpm.go.id/assets/images/bkpm-ico/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="//www.bkpm.go.id/assets/images/bkpm-ico/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="//www.bkpm.go.id/assets/images/bkpm-ico/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="//www.bkpm.go.id/assets/images/bkpm-ico/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="//www.bkpm.go.id/assets/images/bkpm-ico/favicon-16x16.png">
  <link rel="manifest" href="//www.bkpm.go.id/assets/images/bkpm-ico/manifest.json">
  <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
  <title>{{setting('site.title')}} | {{setting('site.description')}}</title>
  <link rel="apple-touch-icon" href="apple-touch-icon.png">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
  <link rel="stylesheet" href="{{asset('frontend/styles/vendor.css')}}">
  <link rel="stylesheet" href="{{asset('frontend/styles/fontawesome-all.css')}}">
  <link rel="stylesheet" href="{{asset('frontend/styles/main.css')}}">
  <script src="{{asset('frontend/scripts/vendor/modernizr.js')}}"></script>
</head>

<body>
  <!--[if IE]><p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p><![endif]-->
  <div id="wrapper">
    <div class="header">
      <div class="top">
        <div class="container">
          <div class="logo desktop"><a href="{{url('/')}}">
            <img style="width: 160px;" src="{{asset('storage/'.setting('site.logo'))}}" alt="" class="img-fluid"></a></div>
        </div>
        <div class="mobile showMobile"><button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
            aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="logo"><a href="{{url('/')}}"><img src="{{asset('storage/'.setting('site.logo'))}}" alt="" class="img-fluid"></a></div>
        </div>
      </div>
      <div class="menu-wrapper">
        <div class="container">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="clearfix full">
                <div class="navbar-nav float-left">
                  <a class="nav-item nav-link active" href="{{url('/')}}">Beranda </a>
                  @foreach (menuItem('frontend')->getItem as $m)
                  <a class="nav-item nav-link" target="{{$m->target}}" href="{{url($m->url)}}">{{ucwords($m->title)}}</a>
                  @endforeach
                  
                </div>
                <div class="float-right right-menu">
                  <div class="navbar-nav">
                    @auth
                      <a href="{{ url('/my-course') }}">Diklat Saya</a>
                      <a href="javascript:" onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                            Keluar</a>
                      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                          @csrf
                      </form>
                    @else
                      <a href="{{ route('login') }}">Masuk</a>

                      @if (Route::has('register'))
                          <a href="{{ route('register') }}">Registrasi</a>
                      @endif
                    @endauth
                  </div>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>
      <div class="slider-wrapper">
        <div class="slider single-item">
          @foreach (getSlider() as $s)
            <div class="block">
              <div class="img"><img src="{{asset('storage/'.$s->image)}}" alt="{{ucwords($s->title)}}" class="img-fluid"></div>
              <div class="column">
                <h1>{{ucwords($s->title)}}</h1>
                @if (!empty($s->button))
                  <a href="{{$s->url}}" class="btn" >{{ucwords($s->button)}} <i class="fas fa-arrow-right"></i></A>
                @endif
              </div>
            </div>
          @endforeach
        </div>
      </div>
      @if (!empty(setting('site.video_text')))
      <div class="content-wrapper bg-light m-0 py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-6 col-12">
              <div class="embed-responsive embed-responsive-16by9">
                <video autoplay loop controls class="embed-responsive-item">
                  <source src="{{asset('storage/video/opening_kepala_bkpm.mp4')}}" type="video/mp4">
                </video>
              </div>
            </div>
            <div class="offset-md-1 col-md-5 col-12">
              {!!setting('site.video_text')!!}
            </div>
          </div>
        </div>
      </div>
      @endif
      <div class="content-wrapper">
        <div class="container">
          <h1 class="title">fasilitas E-Learning BKPM</h1>
          <h4 class="subtitle">Merupakan sebuah metode pelatihan berbasis online, yang di selenggarakan untuk para
            peserta diklat BKPM</h4>
          <div class="column">
            <div class="row">
              <div class="col-md-4 col-12">
                <div class="block">
                  <div class="row">
                    <div class="col-3 imgx">
                      <div class="img"><img src="{{asset('frontend/images/ico-mobile.png')}}" alt="" class="img-fluid"></div>
                    </div>
                    <div class="col-9">
                      <div class="name">Mobile Delivery</div>
                      <div class="desc">Bisa diakses kapan saja dan dimana saja melalui ponsel.</div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4 col-12">
                <div class="block">
                  <div class="row">
                    <div class="col-3 imgx">
                      <div class="img"><img src="{{asset('frontend/images/ico-video.png')}}" alt="" class="img-fluid"></div>
                    </div>
                    <div class="col-9">
                      <div class="name">Video Learning</div>
                      <div class="desc">Materi pembelajaran berupa video learning</div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4 col-12">
                <div class="block">
                  <div class="row">
                    <div class="col-3 imgx">
                      <div class="img"><img src="{{asset('frontend/images/ico-video-2.png')}}" alt="" class="img-fluid"></div>
                    </div>
                    <div class="col-9">
                      <div class="name">Video Conference</div>
                      <div class="desc">Nikmati fasilitas video konferensi dari Widyaswara dan diskusi online</div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4 col-12">
                <div class="block">
                  <div class="row">
                    <div class="col-3 imgx">
                      <div class="img"><img src="{{asset('frontend/images/ico-quiz.png')}}" alt="" class="img-fluid"></div>
                    </div>
                    <div class="col-9">
                      <div class="name">Popup Quiz</div>
                      <div class="desc">Quiz akan muncul pada saat video pembelajaran sedang berputar</div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4 col-12">
                <div class="block">
                  <div class="row">
                    <div class="col-3 imgx">
                      <div class="img"><img src="{{asset('frontend/images/ico-ujian.png')}}" alt="" class="img-fluid"></div>
                    </div>
                    <div class="col-9">
                      <div class="name">Ujian Online</div>
                      <div class="desc">Ujian dilaksanakan setelah seluruh video pembelajaran telah selesai</div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4 col-12">
                <div class="block">
                  <div class="row">
                    <div class="col-3 imgx">
                      <div class="img"><img src="{{asset('frontend/images/ico-certificate.png')}}" alt="" class="img-fluid"></div>
                    </div>
                    <div class="col-9">
                      <div class="name">E-Certificate</div>
                      <div class="desc">Sertifikat yang dapat dicetak sendiri, setelah menyelesaikan ujian</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="flow-wrapper">
        <div class="container">
          <div class="column">
            <div class="title">Alur Cara Belajar</div>
            <div class="img"><img src="{{asset('storage/'.setting('site.flow_belajar'))}}" alt="" class="img-fluid"></div>
          </div>
        </div>
      </div>
      <div class="diklat-wrapper">
        <div class="container">
          <div class="row tops">
            <div class="col-md-6 col-12">
              <div class="title">Kumpulan Diklat</div>
            </div>
            <div class="col-md-6 col-12">
              <div class="more"><a href="{{url('diklat')}}">Lihat semua <i class="fas fa-angle-right"></i></a></div>
            </div>
          </div>
          <div class="list-diklat">
            <div class="slider single-item2">
              @foreach ($diklat as $d)
                {{-- @dump($d) --}}
                <div class="block" onclick="window.location.href = `{!!url('diklat/'.$d->id)!!}`">
                    <div class="img"><img src="{{asset('storage/'.$d->image)}}" alt="" class="img-fluid">
                    </div>
                    <div class="content">
                        @if (!is_null($d->category))
                            <div class="cat"><a href="#">{{ucwords($d->category->name)}}</a></div>
                        @endif
                        <div class="title-post"><a href="#">{{ucwords($d->title)}}</a></div>
                    </div>
                </div>
              @endforeach
            </div>
          </div>
        </div>
      </div>
      <div class="footer">
        <div class="container">
          <div class="copy">Copyright &copy; 2018 <strong>elearning.bkpm.go.id</strong>, All right reserved.</div>
        </div>
      </div>
    </div>
  </div>
  <script src="{{asset('frontend/scripts/vendor.js')}}"></script>
  <script src="{{asset('frontend/scripts/main.js')}}"></script>
  <script src="{{asset('frontend/scripts/sweetalert.min.js')}}"></script>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-145618947-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-145618947-1');
  </script>

  <script>
    $(document).ready(function(){
      @if (session()->has('success_msg'))
        swal ( "Sukses!" ,  `{!!session()->get('success_msg')!!}` ,  "success" )
      @endif
      @if (session()->get('error_msg'))
        swal ( "Gagal!" ,  `{!!session()->get('error_msg')!!}` ,  "error" )
      @endif
      @if (session()->get('warning_msg'))
        swal ( "Awas!" ,  `{!!session()->get('warning_msg')!!}` ,  "warning" )
      @endif
      @if (session()->get('info_msg'))
        swal ( "Info!" ,  `{!!session()->get('info_msg')!!}` ,  "info" )
      @endif
    })
  </script>
</body>

</html>
